spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:discountService
    username: sa
    password: password
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
